### ISSUE TITLE
examples/ad_account_ad_videos_post.js does not work

### ISSUE THREAD

**Issue by yuvalk** [facebook/facebook-nodejs-business-sdk#101]
undefined POST https://graph.facebook.com/v3.2/act_2205959226324752/advideos?access_token=<ACCESS_TOKEN>
            {"source":"./sara3_1.mp4","id":"act_2205959226324752"}
An error occurred while processing, Create Video Creative
Error Message:FacebookRequestError: Unsupported post request.
Error Stack:Error
    at FacebookRequestError.FacebookError [as constructor] (/git/js/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:319:16)
    at new FacebookRequestError (/git/js/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:341:129)
    at /git/js/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:507:15
    at tryCatcher (/git/js/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/git/js/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/git/js/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/git/js/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/git/js/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/git/js/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/git/js/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/git/js/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/git/js/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

**Comment by jingping2015** [comment]
Hey, thanks for your comment! 
Did you try call API directly. Looks like this is an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!

**Comment by yuvalk** [comment]
I don't think so.
it seems like a nodejs specific issue,
I found out that this kind of call:
`const advideo = new AdVideo(null, null, 'act_' + accountId);
advideo.set('filepath', './sara3_1.mp4');
advideo.create().then(
    function(result) {
        advideo.waitUntilEncodingReady();
    },
    function (result) {
        utils.errorFunction("Create Video Creative");
    }
);`
works..

I think it is related to video encoding wherein the first format (of the example) - 
the AdAccount.createAdVideo issue a direct call to the graph API (with 'source' parameter) 
that just wont work because source should be multipar/form-data encoded

whereas my call (as seen above) AdVideo.create utilize the video-uploader.js 

IMHO - this calls not just to fix the example but also AdAccount.createAdVideo to work similarly.

BTW: the python example works just fine..
