### ISSUE TITLE
Error while running Product Feeds sample code

### ISSUE THREAD

**Issue by yoonwaiyan** [facebook/facebook-nodejs-business-sdk#102]
### Which SDK version are you using?
3.2.8

### What's the issue?
There's an error that seems to fired from the library instead of my syntax error. I copy and pasted the code from [this sample](https://github.com/facebook/facebook-nodejs-business-sdk/blob/f6447a210c030a574003a07115504fbb487c72cf/examples/product_catalog_product_feeds_post_product_feed.js) and used my sandbox access token and catalog id. What's different is I removed api key and secret since they are not used throughout the sample.

### Steps/Sample code to reproduce the issue
https://repl.it/repls/FoolishNextAddresses

#### Observed Results:
This is the error I received within the REPL console:

```
product_feeds api call complete.
Data:{}
=> undefined
undefined POST https://graph.facebook.com/v3.2/329890614305736/product_feeds?access_token=EAAD1YHKulmgBAAGlxjRNoaeGSYex6Jto3kZAm7ZB3c7IaBGM4zawZB4sCT5Mm6NsvDy8FE3AyscLJ73orqD69wZCOUc8ZCpPwY3UNagpSs19bR3Fu5mkUh1U0i1M4iPSPvPTKVstqCucBAOhAGFTZAZAo8CpoDyiiWtlPfVbr8lLGMLgo5fma3VZCIC7mWxbSX0Rn8sRdu6Frk1vNv6FZACDs
            {"name":"Test Feed","schedule":{"interval":"DAILY","url":"http://www.example.com/sample_feed.tsv","hour":"22"},"id":"329890614305736"}
(node:84) UnhandledPromiseRejectionWarning: Error
    at FacebookRequestError.FacebookError [as constructor] (/home/runner/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:319:16)
    at new FacebookRequestError (/home/runner/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:341:129)
    at /home/runner/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:507:15
    at tryCatcher (/home/runner/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/runner/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/runner/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/runner/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/runner/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/runner/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/runner/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
(node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:84) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Expected Results:
Expected it to register the product feed to my facebook catalog successfully.

**Comment by michaelwclark** [comment]
Firstly, You are going to want to change your access_token as it's public now in this thread. Secondly it's not the SDK, but rather your code not handling this error.

updating your code a bit to:
```
const product_feeds = (new ProductCatalog(id)).createProductFeed(
  fields,
  params
).catch(e=>console.log('err',e));
```
will result in:

```
 status: 400,
  response:
   { error:
      { message:
         'Unsupported post request. Object with ID \'329890614305736\' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api',
        type: 'GraphMethodException',
        code: 100,
        error_subcode: 33,
        fbtrace_id: 'D/P7chomC1T' } },
  method: 'POST',
  url:
   'https://graph.facebook.com/v3.2/329890614305736/product_feeds?access_token=EAAD1YHKulmgBAAGlxjRNoaeGSYex6Jto3kZAm7ZB3c7IaBGM4zawZB4sCT5Mm6NsvDy8FE3AyscLJ73orqD69wZCOUc8ZCpPwY3UNagpSs19bR3Fu5mkUh1U0i1M4iPSPvPTKVstqCucBAOhAGFTZAZAo8CpoDyiiWtlPfVbr8lLGMLgo5fma3VZCIC7mWxbSX0Rn8sRdu6Frk1vNv6FZACDs',
  data:
   { name: 'Test Feed',
     schedule:
      { interval: 'DAILY',
        url: 'http://www.example.com/sample_feed.tsv',
        hour: '22' },
     id: '329890614305736' } }
```


This message indidcates a permissions error likely with your access_token and the business id. It's also possible you need to inject an appSecretProof into your params to make this work. Currently the SDK isn't great at that, but you can send appsecret_proof explicitly in your params. 

If you're unsure on how to handle appsecrets the checkout [Securing Requests](https://developers.facebook.com/docs/graph-api/securing-requests/) or hit me up, i'll walk you through generating or pointing you to other helper modules to do so.

**Comment by michaelwclark** [comment]
@yoonwaiyan  you should likely close this issue. Also the latest chagnes have been published in the `@denimlabs/facebook-nodejs-business-sdk`
