### ISSUE TITLE
details missing from errors

### ISSUE THREAD

**Issue by danny-waite** [facebook/facebook-nodejs-business-sdk#147]
### Which SDK version are you using?
6.0.1

### What's the issue?
Not getting detail in the thrown error

### Steps/Sample code to reproduce the issue
 try {
      let creative = await account.createAdCreative([], params);
      return creative.id;
    } catch (error) {
      console.log(JSON.stringify(error));
      throw error;
    }

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
If I make a call directly to the HTTP endpoint I get plenty of information, eg
```
{
  "error": {
    "message": "Invalid parameter",
    "type": "OAuthException",
    "code": 100,
    "error_subcode": 1487833,
    "is_transient": true,
    "error_user_title": "Image wasn't downloaded",
    "error_user_msg": "Your image, https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3\/yu\/r\/66zXtGTxCWr.png, couldn't be downloaded. Please wait a few minutes and try again.",
    "fbtrace_id": "Alf3Nj48VMXKzCrXm4gyTjd"
  }
}
```

**Comment by jingping2015** [comment]
What's the output of `console.log(JSON.stringify(error));`, did you ever come to this step ?

**Comment by danny-waite** [comment]
So here is the stringified error:
```
{"name":"FacebookRequestError","stack":"Error: \n    at FacebookRequestError.FacebookError [as constructor] (/adsmanager-lib/node_modules/facebook-nodejs-business-sdk/dist/exceptions.js:18:16)\n    at new FacebookRequestError (/adsmanager-lib/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:346:129)\n    at /adsmanager-lib/node_modules/facebook-nodejs-business-sdk/dist/api.js:145:15\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","method":"POST","url":"https://graph.facebook.com/v6.0/act_12c/ads?access_token=abc","data":{"name":"test ad","adset_id":"123","creative":{"creative_id":"456"},"status":"PAUSED"}}
```

and this is the what was in the HTTP response
```
{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"abc"}}
```

**Comment by rmeloni** [comment]
I'm receiving the same error:

error: {
      message: 'Invalid parameter',
      type: 'OAuthException',
      code: 100,
      error_subcode: 1487833,
      is_transient: true,
      error_user_title: "Image Wasn't Downloaded",
      error_user_msg: "Your image, https://payeverproduction.blob.core.windows.net/products/1bb551fc-d4c7-4753-9b1a-3a8c5a74aa3a-Screenshot2020-02-07at09.55.28, couldn't be downloaded. Please wait a few minutes and try again.",
      fbtrace_id: 'AlvOsqlgt6P_e2FAZIgUCG7'
    }

**Comment by danny-waite** [comment]
guys, seriously, not getting the detail in the error is really frustrating, any chance of getting this fixed? @jingping2015

**Comment by nabejohn** [comment]
I think this is still an issue. even with latest SDK versions.
Is it resolved ?

**Comment by humkins** [comment]
The issue is reproduced for me with SDK v12. I think it would be a good idea to provide specific information what is wrong, which exactly parameter is bad.
