### ISSUE TITLE
Broken Report Id in Async Insight Reports

### ISSUE THREAD

**Issue by burakim** [facebook/facebook-nodejs-business-sdk#188]
### Which SDK version are you using?
9.0.2
### What's the issue?
After requesting an async AdReportRun to fetch insight data and receiving a valid report id from the getInsightsAsync function, SDK throws the following error message when we request the status of the AdReportRun object.

```
Error: AdReportRun Id not defined
    at AdReportRun.getId (/Users/xxx/Projects/VSCode/xxxx/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:1649:15)
    at AdReportRun.getNodePath (/Users/xx/Projects/VSCode/xxxx/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:1675:19)
    at AdReportRun.read (/Users/xxxx/Projects/VSCode/xxxx/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:1709:27)
    at AdReportRun.get (/Users/xxxx/Projects/VSCode/vidmob-analytics-verification-tools/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:4532:19)
```

It looks like the function that is responsible for creating an AdReportRun request, is not passing the correct id field to the function that checks the status of the AdReportRun request.

### Steps/Sample code to reproduce the issue

```
    const reportRequestResponse = await fb_account_entity.getInsightsAsync(fields, parameters);
    const fields = [
      AdReportRun.Fields.id,
      AdReportRun.Fields.async_percent_completion, AdReportRun.Fields.async_status,
    ];
    const report  = new AdReportRun(reportRequestResponse.id);
    const reportStatus = await report.get(fields);
```

#### Expected Results:

  * What did you expect to happen?
Return the status of the AdReportRun request.

I was able to solve the issue by adding a fallback mechanism that uses the first element of the argument array in case the data variable does not have a valid report id.  The fallback mechanism is located in the AdReportRun function of the cjs.js file can be seen below. The cjs.js file is transcomplied output js file and the original code that has the issue may be in the constructor of the AdReportRun class.

```   if (data.report_run_id) {
      _this.id = data.report_run_id;
    } else {
      _this.id = arguments[0]
    }
```

**Comment by smbkr** [comment]
Bumping because there are a few related issues that have been closed due to staleness, with no response from Facebook.

https://github.com/facebook/facebook-nodejs-business-sdk/issues/119
https://github.com/facebook/facebook-nodejs-business-sdk/issues/140
