### ISSUE TITLE
details missing from errors

### ISSUE THREAD

**Issue by nabejohn** [facebook/facebook-nodejs-business-sdk#195]
same issue [ details missing from errors #147 ].  but it is closed.

### Which SDK version are you using?
10.0.0
### What's the issue?
Not getting detail in the thrown error

### Steps/Sample code to reproduce the issue

```
try {
const creative = await account.createAdCreative([], params);
return creative.id;
} catch (error) {
console.error(error);
throw error;
}
```

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
console.log output is below. (masking ACCOUNT_ID, ACCESS_TOKEN, PAGE_ID, INSTAGRAM_ACTOR_ID)
```
FacebookRequestError {
      name: 'FacebookRequestError',
      message: undefined,
      stack: 'Error: \n' +
        '    at FacebookRequestError.FacebookError [as constructor] (/test/node_modules/facebook-nodejs-business-sdk/dist/exceptions.js:18:16)\n' +
        '    at new FacebookRequestError (/test/node_modules/facebook-nodejs-business-sdk/dist/cjs.js:373:129)\n' +
        '    at /test/node_modules/facebook-nodejs-business-sdk/dist/api.js:148:15\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:93:5)',
      status: undefined,
      response: undefined,
      headers: undefined,
      method: 'POST',
      url: 'https://graph.facebook.com/v10.0/act_<ACCOUNT_ID>/adcreatives?access_token=<ACCESS_TOKEN>',
      data: {
        name: 'test',
        title: 'test',
        body: 'test',
        object_story_spec: {
          page_id: '<PAGE_ID>',
          instagram_actor_id: '<INSTAGRAM_ACTOR_ID>',
          link_data: [Object]
        },
        id: 'act_<ACCOUNT_ID>'
      }
    }
```

#### Expected Results:

  * What did you expect to happen?
I make a call on Graph API Explorer. I get error message below.
```
{
  "error": {
    "message": "Invalid parameter",
    "type": "OAuthException",
    "code": 100,
    "error_subcode": 1772145,
    "is_transient": false,
    "error_user_title": "ページバックアカウントを使用できません",
    "error_user_msg": "Instagramアクターは、ページにリンク済みのInstagramアカウントにしてください。",
    "fbtrace_id": "A3hy95RlcuYLvHBLnv06H26"
  }
}
```
I want `FacebookRequestError` to include error message (ex. `error_user_title`, `error_user_msg` ).
https://github.com/facebook/facebook-nodejs-business-sdk/blob/master/src/exceptions.js#L80-L82
Should `FacebookRequestError.message` contain `error_user_title` and `error_user_msg` ?
why `FacebookRequestError.message` is undefined ?

**Comment by nabejohn** [comment]
resolved. because of bugfix ? maybe...
