### ISSUE TITLE
Cannot access request error response from FacebookRequestError

### ISSUE THREAD

**Issue by GHSVerde** [facebook/facebook-nodejs-business-sdk#234]
### Which SDK version are you using?
`14.0.0`

### What's the issue?
Can't access the message or code response from the `FacebookRequestError` object. I use the SDK for creating ads through a platform and every time something goes wrong with the request, the SDK returns an instance of `[FacebookRequestError](https://github.com/facebook/facebook-nodejs-business-sdk/blob/main/src/exceptions.js#26)`. 

When I access the object, the only filled properties are: stack, url, method, name, data (with the request payload).

Project setup: Nuxt.js with facebook sdk as a plugin.

### Steps/Sample code to reproduce the issue
1 - On a frontend project, make any invalid request and try to access the status/message from `FacebookRequestMessage` 

#### Observed Results:
```
{
    "name": "FacebookRequestError",
    "stack": "Error\n    at FacebookRequestError.FacebookError [as constructor] (webpack-internal:///./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:351:16)\n    at new FacebookRequestError (webpack-internal:///./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:373:129)\n    at eval (webpack-internal:///./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:671:15)",
    "method": "POST",
    "url": "https://graph.facebook.com/v14.0/act_removed/adcreatives?access_token=removed",
    "data": removed
}
```
The lines from the bundle represents the following: 
351: https://github.com/facebook/facebook-nodejs-business-sdk/blob/main/src/exceptions.js#L18
373: https://github.com/facebook/facebook-nodejs-business-sdk/blob/main/src/exceptions.js#L36
671: https://github.com/facebook/facebook-nodejs-business-sdk/blob/main/src/api.js#L148

#### Expected Results:
Based on the code, it should be

```
{
    "name": "FacebookRequestError",
    "message": --- The observed message from Network tab,
    "method": "POST",
    "status": --- The error Code
    "url": "https://graph.facebook.com/v14.0/act_removed/adcreatives?access_token=removed",
    "data": removed
}
```

**Comment by Gabzmelo** [comment]
I'm having the same issue too :(

**Comment by fuongduyuid** [comment]
I'm facing similar issue.
I'm trying get the insights of ads/campaigns but repeatedly received this error
`CrashReporter: SDK crash detected!
Not be able to find appID, fail to send report to server.`

**Comment by GHSVerde** [comment]
@fuongduyuid I believe your issue is related to configuration other than api response.

My case is about api response and proper `FacebookRequestError` object translation.

**Comment by GHSVerde** [comment]
Is this project abandoned?

**Comment by GHSVerde** [comment]
Tested and [PR 158](https://github.com/facebook/facebook-nodejs-business-sdk/pull/158) Fixed it. can it still be implemented and tested?
