### ISSUE TITLE
Versioning Issues

### ISSUE THREAD

**Issue by yoann-trouillet** [facebook/facebook-nodejs-business-sdk#28]
Hi ,

I am pretty much a noob to nodejs, javascript and the facebook API. So I apologies if this bug report isn't as helpfull as it could be.

I created a new Facebook App (today) and I am trying to get some ad insights (account.getInsights) but running into a versioning issue :

FacebookRequestError: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.12.
    at FacebookRequestError.FacebookError [as constructor] (/Users/yoann/dev/src/track.jackmedia.io/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:319:16)
    at new FacebookRequestError (/Users/yoann/dev/src/track.jackmedia.io/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:341:129)
    at /Users/yoann/dev/src/track.jackmedia.io/node_modules/facebook-nodejs-ads-sdk/dist/cjs.js:507:15
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

Guessing this is related to yesterday 2.12 release : 
https://developers.facebook.com/ads/blog/post/2018/01/30/graph-api-212-release/

Any tips would be much appreciated ...

<img width="815" alt="screen shot 2018-02-01 at 2 42 46 pm" src="https://user-images.githubusercontent.com/19640156/35660100-3cb8ad54-075e-11e8-96bd-ef33998269fb.png">

**Comment by baytelman** [comment]
Having the same issue.

**Comment by scaydogdu** [comment]
update the version in cjs.js and api.js to v2.12
there is no major changes
