### ISSUE TITLE
Error upon getting certain fields across objects

### ISSUE THREAD

**Issue by aamorozov** [facebook/facebook-nodejs-business-sdk#59]
I'm trying to get all data related to campaigns within the account, but when I requesting it with all fields selected I'm getting the following error. If I omit those fields, the data comes back just fine. They all seem to be related to budget, so I am guessing it is a permission error, but I allowed all types of requests within my facebook app and I am a bit at a loss at this point. Thank you

#### Fields that are erroring
```
Campaign.Fields.bid_strategy
Campaign.Fields.budget_remaining,
Campaign.Fields.daily_budget,
Campaign.Fields.lifetime_budget,
```

#### Error stack 

```
 name: 'FacebookRequestError',
  message:
   'Syntax error "Expected name." at character 200: name,id,status,account_id,adlabels,boosted_object_id,brand_lift_studies,budget_rebalance_flag,buying_type,can_create_brand_lift_study,can_use_spend_cap,configured_status,created_time,effective_status,,stop_time',
  
stack:
   'Error at FacebookRequestError.FacebookError [as constructor] (./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:319:16)
at new FacebookRequestError (./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:341:129)
at ./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:507:15
at tryCatcher (./node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (./node_modules/bluebird/js/release/promise.js:689:18)
at Async._drainQueue (./node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (./node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues [as _onImmediate] (./node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:696:18)
at tryOnImmediate (timers.js:667:5)
at processImmediate (timers.js:649:5)',
  status: 400,
  response:
   { error:
      { message:
         'Syntax error "Expected name." at character 200: name,id,status,account_id,adlabels,boosted_object_id,brand_lift_studies,budget_rebalance_flag,buying_type,can_create_brand_lift_study,can_use_spend_cap,configured_status,created_time,effective_status,,stop_time',
        type: 'OAuthException',
        code: 2500,
        fbtrace_id: 'GftS8YdATcr' } },

```

**Comment by aamorozov** [comment]
The same error is occurring with the following fields of AdSet object: 

```
AdSet.Fields.daily_budget,
AdSet.Fields.daily_min_spend_target
AdSet.Fields.daily_spend_cap
AdSet.Fields.lifetime_min_spend_targeta
AdSet.Fields.lifetime_spend_cap
```

**Comment by aamorozov** [comment]
I did notice that, but I am not sure why it's appending an extra coma since it's not coming from my code.

**Comment by MerrickClark** [comment]
Ah ok. So you're only seeing the error when including specific field(s)? Have you narrowed it down to the problem field(s)

**Comment by aamorozov** [comment]
Yes, the fields I've added in the original issue for the Campaign and for the AdSet in the comment above.

**Comment by MerrickClark** [comment]
Can you reproduce the error in Graph Explorer?

**Comment by aamorozov** [comment]
I'll try replicating tonight
