### ISSUE TITLE
Error running SAMPLE_CODE.js

### ISSUE THREAD

**Issue by carlosbbraga** [facebook/facebook-nodejs-business-sdk#96]
I´m having trouble with the sample code facebook gave me.
I haven´t changed a thing and yet I´m cannot run the script. 

Here is the problem: 
undefined GET https://graph.facebook.com/v2.11/act_275008529843364/insights?level=adset&filtering=%5B%7B%22field%22%3A%22delivery_info%22%2C%22operator%22%3A%22IN%22%2C%22value%22%3A%5B%22active%22%2C%22limited%22%5D%7D%5D&breakdowns=%5B%22ad_id%22%5D&time_range=%7B%22since%22%3A%222018-12-16%22%2C%22until%22%3A%222019-01-15%22%7D&fields=results%2Cresult_rate%2Cspend%2Ccost_per_result%2Ccpp%2Ccpm%2Cactions%3Apage_engagement%2Cactions%3Apost_engagement%2Cactions%3Aleadgen.other&access_token=<<ACCESTOKEN REMOVED FOR SAFETY REASONS>>
            {}
{ Error
    at FacebookRequestError.FacebookError [as constructor] (D:\Pessoal\Study\facebook-leads\node_modules\facebook-nodejs-ads-sdk\dist\cjs.js:319:16)
    at new FacebookRequestError (D:\Pessoal\Study\facebook-leads\node_modules\facebook-nodejs-ads-sdk\dist\cjs.js:341:129)
    at D:\Pessoal\Study\facebook-leads\node_modules\facebook-nodejs-ads-sdk\dist\cjs.js:507:15
    at tryCatcher (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\Pessoal\Study\facebook-leads\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  name: 'FacebookRequestError',
  message: 'Syntax error "Expected "(", got end of string" at character 119: results,result_rate,spend,cost_per_result,cpp,cpm,actions:page_engagement,actions:post_engagement,actions:leadgen.other',
  stack: 'Error\n    at FacebookRequestError.FacebookError [as constructor] (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\facebook-nodejs-ads-sdk\\dist\\cjs.js:319:16)\n    at new FacebookRequestError (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\facebook-nodejs-ads-sdk\\dist\\cjs.js:341:129)\n    at D:\\Pessoal\\Study\\facebook-leads\\node_modules\\facebook-nodejs-ads-sdk\\dist\\cjs.js:507:15\n    at tryCatcher (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\promise.js:512:31)\n    at Promise._settlePromise (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\promise.js:569:18)\n    at Promise._settlePromise0 (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\promise.js:614:10)\n    at Promise._settlePromises (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\promise.js:690:18)\n    at _drainQueueStep (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\async.js:138:12)\n    at _drainQueue (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\async.js:131:9)\n    at Async._drainQueues (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\async.js:147:5)\n    at Immediate.Async.drainQueues (D:\\Pessoal\\Study\\facebook-leads\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)',
  status: 400,
  response:
   { error:
      { message: 'Syntax error "Expected "(", got end of string" at character 119: results,result_rate,spend,cost_per_result,cpp,cpm,actions:page_engagement,actions:post_engagement,actions:leadgen.other',
        type: 'OAuthException',
        code: 2500,
        fbtrace_id: 'DcYClntP5z5' } },
  method: 'GET',
  url: 'https://graph.facebook.com/v2.11/act_275008529843364/insights?level=adset&filtering=%5B%7B%22field%22%3A%22delivery_info%22%2C%22operator%22%3A%22IN%22%2C%22value%22%3A%5B%22active%22%2C%22limited%22%5D%7D%5D&breakdowns=%5B%22ad_id%22%5D&time_range=%7B%22since%22%3A%222018-12-16%22%2C%22until%22%3A%222019-01-15%22%7D&fields=results%2Cresult_rate%2Cspend%2Ccost_per_result%2Ccpp%2Ccpm%2Cactions%3Apage_engagement%2Cactions%3Apost_engagement%2Cactions%3Aleadgen.other&access_token=<<ACCESTOKEN REMOVED FOR SAFETY REASONS>>',
  data: {} }

**Comment by Hquestion** [comment]
Did you fixed the problem? I run into the same problem.Could you help me?
